list: $/yamobile/locations/models/phone/columns.yaml
modelClass: Yamobile\Locations\Models\Phone
title: Phones
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'yamobile/locations/phones/update/:id'
