list: $/yamobile/locations/models/location/columns.yaml
modelClass: Yamobile\Locations\Models\Location
title: Locations
noRecordsMessage: "backend::lang.list.no_records"
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
  buttons: list_toolbar
  search:
    prompt: "backend::lang.list.search_prompt"
recordUrl: "yamobile/locations/locations/update/:id"
