list: $/yamobile/locations/models/detail/columns.yaml
modelClass: Yamobile\Locations\Models\Detail
title: Details
noRecordsMessage: "backend::lang.list.no_records"
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
  buttons: list_toolbar
  search:
    prompt: "backend::lang.list.search_prompt"
recordUrl: "yamobile/locations/details/update/:id"
